/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';
import { Template } from '../../models/template';

export interface GetTemplates$Params {

/**
 * Tenant ID to filter templates
 */
  tenantId: string;
}

export function getTemplates(http: HttpClient, rootUrl: string, params: GetTemplates$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponse & {
'data'?: Array<Template>;
}>> {
  const rb = new RequestBuilder(rootUrl, getTemplates.PATH, 'get');
  if (params) {
    rb.query('tenantId', params.tenantId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponse & {
      'data'?: Array<Template>;
      }>;
    })
  );
}

getTemplates.PATH = '/templates';
