/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentType } from '../../models/document-type';
import { Template } from '../../models/template';
import { TemplateCategory } from '../../models/template-category';
import { TemplateStatus } from '../../models/template-status';

export interface UpdateTemplate$Params {
  id: string;
      body: {

/**
 * New DOCX template file (optional, replaces existing file)
 */
'file'?: Blob;
'name'?: string;
'description'?: string;
'category'?: TemplateCategory;
'documentType'?: DocumentType;
'status'?: TemplateStatus;
'startDate'?: string;
'endDate'?: string;
}
}

export function updateTemplate(http: HttpClient, rootUrl: string, params: UpdateTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<Template>> {
  const rb = new RequestBuilder(rootUrl, updateTemplate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Template>;
    })
  );
}

updateTemplate.PATH = '/templates/{id}';
