/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Execution } from '../../models/execution';

export interface CancelExecution$Params {
  id: string;
}

export function cancelExecution(http: HttpClient, rootUrl: string, params: CancelExecution$Params, context?: HttpContext): Observable<StrictHttpResponse<Execution>> {
  const rb = new RequestBuilder(rootUrl, cancelExecution.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Execution>;
    })
  );
}

cancelExecution.PATH = '/executions/{id}/cancel';
