/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';
import { Execution } from '../../models/execution';
import { ExecutionStatus } from '../../models/execution-status';

export interface GetExecutions$Params {

/**
 * Filter by template ID
 */
  templateId?: string;

/**
 * Filter by execution status
 */
  status?: ExecutionStatus;

/**
 * Page number for pagination
 */
  page?: number;

/**
 * Number of items per page
 */
  size?: number;
}

export function getExecutions(http: HttpClient, rootUrl: string, params?: GetExecutions$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponse & {
'data'?: Array<Execution>;
}>> {
  const rb = new RequestBuilder(rootUrl, getExecutions.PATH, 'get');
  if (params) {
    rb.query('templateId', params.templateId, {});
    rb.query('status', params.status, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponse & {
      'data'?: Array<Execution>;
      }>;
    })
  );
}

getExecutions.PATH = '/executions';
