/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Execution } from '../../models/execution';
import { LaunchExecutionRequest } from '../../models/launch-execution-request';

export interface LaunchExecution$Params {
      body: LaunchExecutionRequest
}

export function launchExecution(http: HttpClient, rootUrl: string, params: LaunchExecution$Params, context?: HttpContext): Observable<StrictHttpResponse<Execution>> {
  const rb = new RequestBuilder(rootUrl, launchExecution.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Execution>;
    })
  );
}

launchExecution.PATH = '/executions';
