/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Metadata } from '../models/metadata';
export interface ApiResponse {

  /**
   * Response data
   */
  data?: {
};
  metadata?: Metadata;
}
