/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExecutionStatus } from '../models/execution-status';
export interface Execution {
  convertToPdf?: boolean;
  createdBy: string;

  /**
   * Date when the execution process was created
   */
  createdDate: string;

  /**
   * Duration in milliseconds
   */
  duration?: number;
  endTime?: string;
  errorMessage?: string;
  executionId: string;
  generatedFiles?: Array<{
'fileName'?: string;
'downloadUrl'?: string;
}>;
  numberOfDocuments: number;
  startTime: string;
  status: ExecutionStatus;
  templateId: string;
}
