/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExecutionStatus } from './execution-status';

/**
 * Each possible value of `ExecutionStatus`
 */
export const EXECUTION_STATUS: ExecutionStatus[] = [
  'PENDING',
  'RUNNING',
  'COMPLETED',
  'FAILED',
  'CANCELLED'
];