/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LaunchExecutionRequest {

  /**
   * Whether to convert generated documents to PDF
   */
  convertToPdf: boolean;

  /**
   * Number of documents to generate
   */
  numberOfDocuments: number;
  templateId: string;
}
