/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Metadata {

  /**
   * Current page number
   */
  page?: number;

  /**
   * Number of items per page
   */
  pageSize?: number;

  /**
   * Total number of items
   */
  total?: number;

  /**
   * Total number of pages
   */
  totalPages?: number;
}
