/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TemplateCategory } from './template-category';

/**
 * Each possible value of `TemplateCategory`
 */
export const TEMPLATE_CATEGORY: TemplateCategory[] = [
  'IBI',
  'IVTM',
  'IAE',
  'RECAUDACION',
  'NOTIFICACION'
];