/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TemplateStatus } from './template-status';

/**
 * Each possible value of `TemplateStatus`
 */
export const TEMPLATE_STATUS: TemplateStatus[] = [
  'ACTIVE',
  'INACTIVE',
  'ARCHIVED'
];