/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Metadata } from './Metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
} from './Metadata';

/**
 * 
 * @export
 * @interface ApiResponse1
 */
export interface ApiResponse1 {
    /**
     * Response data
     * @type {object}
     * @memberof ApiResponse1
     */
    data?: object;
    /**
     * 
     * @type {Metadata}
     * @memberof ApiResponse1
     */
    metadata?: Metadata;
}

/**
 * Check if a given object implements the ApiResponse1 interface.
 */
export function instanceOfApiResponse1(value: object): boolean {
    return true;
}

export function ApiResponse1FromJSON(json: any): ApiResponse1 {
    return ApiResponse1FromJSONTyped(json, false);
}

export function ApiResponse1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponse1 {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'metadata': json['metadata'] == null ? undefined : MetadataFromJSON(json['metadata']),
    };
}

export function ApiResponse1ToJSON(value?: ApiResponse1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'],
        'metadata': MetadataToJSON(value['metadata']),
    };
}

