/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DocumentType = {
    CartaPago: 'CARTA_PAGO',
    Notificacion: 'NOTIFICACION',
    Recibo: 'RECIBO',
    Resolucion: 'RESOLUCION',
    Edicto: 'EDICTO'
} as const;
export type DocumentType = typeof DocumentType[keyof typeof DocumentType];


export function instanceOfDocumentType(value: any): boolean {
    return Object.values(DocumentType).includes(value);
}

export function DocumentTypeFromJSON(json: any): DocumentType {
    return DocumentTypeFromJSONTyped(json, false);
}

export function DocumentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentType {
    return json as DocumentType;
}

export function DocumentTypeToJSON(value?: DocumentType | null): any {
    return value as any;
}

