/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExecutionGeneratedFilesInner } from './ExecutionGeneratedFilesInner';
import {
    ExecutionGeneratedFilesInnerFromJSON,
    ExecutionGeneratedFilesInnerFromJSONTyped,
    ExecutionGeneratedFilesInnerToJSON,
} from './ExecutionGeneratedFilesInner';
import type { ExecutionStatus } from './ExecutionStatus';
import {
    ExecutionStatusFromJSON,
    ExecutionStatusFromJSONTyped,
    ExecutionStatusToJSON,
} from './ExecutionStatus';

/**
 * 
 * @export
 * @interface Execution
 */
export interface Execution {
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    executionId: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    templateId: string;
    /**
     * 
     * @type {ExecutionStatus}
     * @memberof Execution
     */
    status: ExecutionStatus;
    /**
     * 
     * @type {number}
     * @memberof Execution
     */
    numberOfDocuments: number;
    /**
     * 
     * @type {boolean}
     * @memberof Execution
     */
    convertToPdf?: boolean;
    /**
     * Date when the execution process was created
     * @type {Date}
     * @memberof Execution
     */
    createdDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Execution
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof Execution
     */
    endTime?: Date;
    /**
     * Duration in milliseconds
     * @type {number}
     * @memberof Execution
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    createdBy: string;
    /**
     * 
     * @type {string}
     * @memberof Execution
     */
    errorMessage?: string;
    /**
     * 
     * @type {Array<ExecutionGeneratedFilesInner>}
     * @memberof Execution
     */
    generatedFiles?: Array<ExecutionGeneratedFilesInner>;
}

/**
 * Check if a given object implements the Execution interface.
 */
export function instanceOfExecution(value: object): boolean {
    if (!('executionId' in value)) return false;
    if (!('templateId' in value)) return false;
    if (!('status' in value)) return false;
    if (!('numberOfDocuments' in value)) return false;
    if (!('createdDate' in value)) return false;
    if (!('startTime' in value)) return false;
    if (!('createdBy' in value)) return false;
    return true;
}

export function ExecutionFromJSON(json: any): Execution {
    return ExecutionFromJSONTyped(json, false);
}

export function ExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Execution {
    if (json == null) {
        return json;
    }
    return {
        
        'executionId': json['executionId'],
        'templateId': json['templateId'],
        'status': ExecutionStatusFromJSON(json['status']),
        'numberOfDocuments': json['numberOfDocuments'],
        'convertToPdf': json['convertToPdf'] == null ? undefined : json['convertToPdf'],
        'createdDate': (new Date(json['createdDate'])),
        'startTime': (new Date(json['startTime'])),
        'endTime': json['endTime'] == null ? undefined : (new Date(json['endTime'])),
        'duration': json['duration'] == null ? undefined : json['duration'],
        'createdBy': json['createdBy'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'generatedFiles': json['generatedFiles'] == null ? undefined : ((json['generatedFiles'] as Array<any>).map(ExecutionGeneratedFilesInnerFromJSON)),
    };
}

export function ExecutionToJSON(value?: Execution | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'executionId': value['executionId'],
        'templateId': value['templateId'],
        'status': ExecutionStatusToJSON(value['status']),
        'numberOfDocuments': value['numberOfDocuments'],
        'convertToPdf': value['convertToPdf'],
        'createdDate': ((value['createdDate']).toISOString()),
        'startTime': ((value['startTime']).toISOString()),
        'endTime': value['endTime'] == null ? undefined : ((value['endTime']).toISOString()),
        'duration': value['duration'],
        'createdBy': value['createdBy'],
        'errorMessage': value['errorMessage'],
        'generatedFiles': value['generatedFiles'] == null ? undefined : ((value['generatedFiles'] as Array<any>).map(ExecutionGeneratedFilesInnerToJSON)),
    };
}

