/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExecutionStatus = {
    Pending: 'PENDING',
    Running: 'RUNNING',
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED'
} as const;
export type ExecutionStatus = typeof ExecutionStatus[keyof typeof ExecutionStatus];


export function instanceOfExecutionStatus(value: any): boolean {
    return Object.values(ExecutionStatus).includes(value);
}

export function ExecutionStatusFromJSON(json: any): ExecutionStatus {
    return ExecutionStatusFromJSONTyped(json, false);
}

export function ExecutionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionStatus {
    return json as ExecutionStatus;
}

export function ExecutionStatusToJSON(value?: ExecutionStatus | null): any {
    return value as any;
}

