/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Execution } from './Execution';
import {
    ExecutionFromJSON,
    ExecutionFromJSONTyped,
    ExecutionToJSON,
} from './Execution';
import type { Metadata } from './Metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
} from './Metadata';

/**
 * 
 * @export
 * @interface ExecutionsGet200Response
 */
export interface ExecutionsGet200Response {
    /**
     * 
     * @type {Array<Execution>}
     * @memberof ExecutionsGet200Response
     */
    data?: Array<Execution>;
    /**
     * 
     * @type {Metadata}
     * @memberof ExecutionsGet200Response
     */
    metadata?: Metadata;
}

/**
 * Check if a given object implements the ExecutionsGet200Response interface.
 */
export function instanceOfExecutionsGet200Response(value: object): boolean {
    return true;
}

export function ExecutionsGet200ResponseFromJSON(json: any): ExecutionsGet200Response {
    return ExecutionsGet200ResponseFromJSONTyped(json, false);
}

export function ExecutionsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ExecutionFromJSON)),
        'metadata': json['metadata'] == null ? undefined : MetadataFromJSON(json['metadata']),
    };
}

export function ExecutionsGet200ResponseToJSON(value?: ExecutionsGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ExecutionToJSON)),
        'metadata': MetadataToJSON(value['metadata']),
    };
}

