/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecutionGeneratedFilesInner
 */
export interface ExecutionGeneratedFilesInner {
    /**
     * 
     * @type {string}
     * @memberof ExecutionGeneratedFilesInner
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionGeneratedFilesInner
     */
    downloadUrl?: string;
}

/**
 * Check if a given object implements the ExecutionGeneratedFilesInner interface.
 */
export function instanceOfExecutionGeneratedFilesInner(value: object): boolean {
    return true;
}

export function ExecutionGeneratedFilesInnerFromJSON(json: any): ExecutionGeneratedFilesInner {
    return ExecutionGeneratedFilesInnerFromJSONTyped(json, false);
}

export function ExecutionGeneratedFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionGeneratedFilesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'downloadUrl': json['downloadUrl'] == null ? undefined : json['downloadUrl'],
    };
}

export function ExecutionGeneratedFilesInnerToJSON(value?: ExecutionGeneratedFilesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fileName': value['fileName'],
        'downloadUrl': value['downloadUrl'],
    };
}

