/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LaunchExecutionRequest
 */
export interface LaunchExecutionRequest {
    /**
     * 
     * @type {string}
     * @memberof LaunchExecutionRequest
     */
    templateId: string;
    /**
     * Number of documents to generate
     * @type {number}
     * @memberof LaunchExecutionRequest
     */
    numberOfDocuments: number;
    /**
     * Whether to convert generated documents to PDF
     * @type {boolean}
     * @memberof LaunchExecutionRequest
     */
    convertToPdf: boolean;
}

/**
 * Check if a given object implements the LaunchExecutionRequest interface.
 */
export function instanceOfLaunchExecutionRequest(value: object): boolean {
    if (!('templateId' in value)) return false;
    if (!('numberOfDocuments' in value)) return false;
    if (!('convertToPdf' in value)) return false;
    return true;
}

export function LaunchExecutionRequestFromJSON(json: any): LaunchExecutionRequest {
    return LaunchExecutionRequestFromJSONTyped(json, false);
}

export function LaunchExecutionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaunchExecutionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['templateId'],
        'numberOfDocuments': json['numberOfDocuments'],
        'convertToPdf': json['convertToPdf'],
    };
}

export function LaunchExecutionRequestToJSON(value?: LaunchExecutionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'templateId': value['templateId'],
        'numberOfDocuments': value['numberOfDocuments'],
        'convertToPdf': value['convertToPdf'],
    };
}

