/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Metadata } from './Metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
} from './Metadata';

/**
 * 
 * @export
 * @interface ModelApiResponse
 */
export interface ModelApiResponse {
    /**
     * Response data
     * @type {object}
     * @memberof ModelApiResponse
     */
    data?: object;
    /**
     * 
     * @type {Metadata}
     * @memberof ModelApiResponse
     */
    metadata?: Metadata;
}

/**
 * Check if a given object implements the ModelApiResponse interface.
 */
export function instanceOfModelApiResponse(value: object): boolean {
    return true;
}

export function ModelApiResponseFromJSON(json: any): ModelApiResponse {
    return ModelApiResponseFromJSONTyped(json, false);
}

export function ModelApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'metadata': json['metadata'] == null ? undefined : MetadataFromJSON(json['metadata']),
    };
}

export function ModelApiResponseToJSON(value?: ModelApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'],
        'metadata': MetadataToJSON(value['metadata']),
    };
}

