/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TemplateCategory = {
    Ibi: 'IBI',
    Ivtm: 'IVTM',
    Iae: 'IAE',
    Recaudacion: 'RECAUDACION',
    Notificacion: 'NOTIFICACION'
} as const;
export type TemplateCategory = typeof TemplateCategory[keyof typeof TemplateCategory];


export function instanceOfTemplateCategory(value: any): boolean {
    return Object.values(TemplateCategory).includes(value);
}

export function TemplateCategoryFromJSON(json: any): TemplateCategory {
    return TemplateCategoryFromJSONTyped(json, false);
}

export function TemplateCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateCategory {
    return json as TemplateCategory;
}

export function TemplateCategoryToJSON(value?: TemplateCategory | null): any {
    return value as any;
}

