/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentType } from './DocumentType';
import {
    DocumentTypeFromJSON,
    DocumentTypeFromJSONTyped,
    DocumentTypeToJSON,
} from './DocumentType';
import type { TemplateCategory } from './TemplateCategory';
import {
    TemplateCategoryFromJSON,
    TemplateCategoryFromJSONTyped,
    TemplateCategoryToJSON,
} from './TemplateCategory';
import type { TemplateStatus } from './TemplateStatus';
import {
    TemplateStatusFromJSON,
    TemplateStatusFromJSONTyped,
    TemplateStatusToJSON,
} from './TemplateStatus';

/**
 * 
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    templateId: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    tenantId: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    description?: string;
    /**
     * 
     * @type {TemplateCategory}
     * @memberof Template
     */
    category?: TemplateCategory;
    /**
     * 
     * @type {DocumentType}
     * @memberof Template
     */
    documentType?: DocumentType;
    /**
     * 
     * @type {TemplateStatus}
     * @memberof Template
     */
    status: TemplateStatus;
    /**
     * 
     * @type {Date}
     * @memberof Template
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Template
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    path?: string;
    /**
     * 
     * @type {Date}
     * @memberof Template
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof Template
     */
    modifiedDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    modifiedBy?: string;
}

/**
 * Check if a given object implements the Template interface.
 */
export function instanceOfTemplate(value: object): boolean {
    if (!('templateId' in value)) return false;
    if (!('tenantId' in value)) return false;
    if (!('code' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function TemplateFromJSON(json: any): Template {
    return TemplateFromJSONTyped(json, false);
}

export function TemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Template {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['templateId'],
        'tenantId': json['tenantId'],
        'code': json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'category': json['category'] == null ? undefined : TemplateCategoryFromJSON(json['category']),
        'documentType': json['documentType'] == null ? undefined : DocumentTypeFromJSON(json['documentType']),
        'status': TemplateStatusFromJSON(json['status']),
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'path': json['path'] == null ? undefined : json['path'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'modifiedDate': json['modifiedDate'] == null ? undefined : (new Date(json['modifiedDate'])),
        'modifiedBy': json['modifiedBy'] == null ? undefined : json['modifiedBy'],
    };
}

export function TemplateToJSON(value?: Template | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'templateId': value['templateId'],
        'tenantId': value['tenantId'],
        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
        'category': TemplateCategoryToJSON(value['category']),
        'documentType': DocumentTypeToJSON(value['documentType']),
        'status': TemplateStatusToJSON(value['status']),
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'path': value['path'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'createdBy': value['createdBy'],
        'modifiedDate': value['modifiedDate'] == null ? undefined : ((value['modifiedDate']).toISOString()),
        'modifiedBy': value['modifiedBy'],
    };
}

