/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Metadata } from './Metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
} from './Metadata';
import type { Template } from './Template';
import {
    TemplateFromJSON,
    TemplateFromJSONTyped,
    TemplateToJSON,
} from './Template';

/**
 * 
 * @export
 * @interface TemplatesGet200Response
 */
export interface TemplatesGet200Response {
    /**
     * 
     * @type {Array<Template>}
     * @memberof TemplatesGet200Response
     */
    data?: Array<Template>;
    /**
     * 
     * @type {Metadata}
     * @memberof TemplatesGet200Response
     */
    metadata?: Metadata;
}

/**
 * Check if a given object implements the TemplatesGet200Response interface.
 */
export function instanceOfTemplatesGet200Response(value: object): boolean {
    return true;
}

export function TemplatesGet200ResponseFromJSON(json: any): TemplatesGet200Response {
    return TemplatesGet200ResponseFromJSONTyped(json, false);
}

export function TemplatesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TemplateFromJSON)),
        'metadata': json['metadata'] == null ? undefined : MetadataFromJSON(json['metadata']),
    };
}

export function TemplatesGet200ResponseToJSON(value?: TemplatesGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TemplateToJSON)),
        'metadata': MetadataToJSON(value['metadata']),
    };
}

