/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TemplateStatus = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE',
    Archived: 'ARCHIVED'
} as const;
export type TemplateStatus = typeof TemplateStatus[keyof typeof TemplateStatus];


export function instanceOfTemplateStatus(value: any): boolean {
    return Object.values(TemplateStatus).includes(value);
}

export function TemplateStatusFromJSON(json: any): TemplateStatus {
    return TemplateStatusFromJSONTyped(json, false);
}

export function TemplateStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateStatus {
    return json as TemplateStatus;
}

export function TemplateStatusToJSON(value?: TemplateStatus | null): any {
    return value as any;
}

