/* tslint:disable */
/* eslint-disable */
/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DocumentType,
  ErrorResponse,
  Execution,
  ExecutionStatus,
  ExecutionsGet200Response,
  LaunchExecutionRequest,
  Template,
  TemplateCategory,
  TemplateStatus,
  TemplatesGet200Response,
} from '../models/index';
import {
    DocumentTypeFromJSON,
    DocumentTypeToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExecutionFromJSON,
    ExecutionToJSON,
    ExecutionStatusFromJSON,
    ExecutionStatusToJSON,
    ExecutionsGet200ResponseFromJSON,
    ExecutionsGet200ResponseToJSON,
    LaunchExecutionRequestFromJSON,
    LaunchExecutionRequestToJSON,
    TemplateFromJSON,
    TemplateToJSON,
    TemplateCategoryFromJSON,
    TemplateCategoryToJSON,
    TemplateStatusFromJSON,
    TemplateStatusToJSON,
    TemplatesGet200ResponseFromJSON,
    TemplatesGet200ResponseToJSON,
} from '../models/index';

export interface ExecutionsGetRequest {
    templateId?: string;
    status?: ExecutionStatus;
    page?: number;
    size?: number;
}

export interface ExecutionsIdCancelPostRequest {
    id: string;
}

export interface ExecutionsIdGetRequest {
    id: string;
}

export interface ExecutionsPostRequest {
    launchExecutionRequest: LaunchExecutionRequest;
}

export interface TemplatesGetRequest {
    tenantId: string;
}

export interface TemplatesIdDeleteRequest {
    id: string;
}

export interface TemplatesIdGetRequest {
    id: string;
}

export interface TemplatesIdPutRequest {
    id: string;
    file?: Blob;
    name?: string;
    description?: string;
    category?: TemplateCategory;
    documentType?: DocumentType;
    status?: TemplateStatus;
    startDate?: Date;
    endDate?: Date;
}

export interface TemplatesPostRequest {
    file: Blob;
    tenantId: string;
    code: string;
    name: string;
    description?: string;
    category?: TemplateCategory;
    documentType?: DocumentType;
    startDate?: Date;
    endDate?: Date;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @summary Get execution history
     * @param {string} [templateId] Filter by template ID
     * @param {ExecutionStatus} [status] Filter by execution status
     * @param {number} [page] Page number for pagination
     * @param {number} [size] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    executionsGetRaw(requestParameters: ExecutionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutionsGet200Response>>;

    /**
     * Get execution history
     */
    executionsGet(requestParameters: ExecutionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutionsGet200Response>;

    /**
     * 
     * @summary Cancel a pending execution
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    executionsIdCancelPostRaw(requestParameters: ExecutionsIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Execution>>;

    /**
     * Cancel a pending execution
     */
    executionsIdCancelPost(requestParameters: ExecutionsIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Execution>;

    /**
     * 
     * @summary Get execution details
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    executionsIdGetRaw(requestParameters: ExecutionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Execution>>;

    /**
     * Get execution details
     */
    executionsIdGet(requestParameters: ExecutionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Execution>;

    /**
     * 
     * @summary Launch a new execution
     * @param {LaunchExecutionRequest} launchExecutionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    executionsPostRaw(requestParameters: ExecutionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Execution>>;

    /**
     * Launch a new execution
     */
    executionsPost(requestParameters: ExecutionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Execution>;

    /**
     * 
     * @summary Get all templates
     * @param {string} tenantId Tenant ID to filter templates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    templatesGetRaw(requestParameters: TemplatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesGet200Response>>;

    /**
     * Get all templates
     */
    templatesGet(requestParameters: TemplatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesGet200Response>;

    /**
     * 
     * @summary Delete template
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    templatesIdDeleteRaw(requestParameters: TemplatesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete template
     */
    templatesIdDelete(requestParameters: TemplatesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get template by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    templatesIdGetRaw(requestParameters: TemplatesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Template>>;

    /**
     * Get template by ID
     */
    templatesIdGet(requestParameters: TemplatesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Template>;

    /**
     * 
     * @summary Update template
     * @param {string} id 
     * @param {Blob} [file] New DOCX template file (optional, replaces existing file)
     * @param {string} [name] 
     * @param {string} [description] 
     * @param {TemplateCategory} [category] 
     * @param {DocumentType} [documentType] 
     * @param {TemplateStatus} [status] 
     * @param {Date} [startDate] 
     * @param {Date} [endDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    templatesIdPutRaw(requestParameters: TemplatesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Template>>;

    /**
     * Update template
     */
    templatesIdPut(requestParameters: TemplatesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Template>;

    /**
     * 
     * @summary Create a new template
     * @param {Blob} file DOCX template file
     * @param {string} tenantId 
     * @param {string} code 
     * @param {string} name 
     * @param {string} [description] 
     * @param {TemplateCategory} [category] 
     * @param {DocumentType} [documentType] 
     * @param {Date} [startDate] 
     * @param {Date} [endDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    templatesPostRaw(requestParameters: TemplatesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Template>>;

    /**
     * Create a new template
     */
    templatesPost(requestParameters: TemplatesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Template>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Get execution history
     */
    async executionsGetRaw(requestParameters: ExecutionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutionsGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['templateId'] != null) {
            queryParameters['templateId'] = requestParameters['templateId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/executions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutionsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get execution history
     */
    async executionsGet(requestParameters: ExecutionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutionsGet200Response> {
        const response = await this.executionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cancel a pending execution
     */
    async executionsIdCancelPostRaw(requestParameters: ExecutionsIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Execution>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling executionsIdCancelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/executions/{id}/cancel`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutionFromJSON(jsonValue));
    }

    /**
     * Cancel a pending execution
     */
    async executionsIdCancelPost(requestParameters: ExecutionsIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Execution> {
        const response = await this.executionsIdCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get execution details
     */
    async executionsIdGetRaw(requestParameters: ExecutionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Execution>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling executionsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/executions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutionFromJSON(jsonValue));
    }

    /**
     * Get execution details
     */
    async executionsIdGet(requestParameters: ExecutionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Execution> {
        const response = await this.executionsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Launch a new execution
     */
    async executionsPostRaw(requestParameters: ExecutionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Execution>> {
        if (requestParameters['launchExecutionRequest'] == null) {
            throw new runtime.RequiredError(
                'launchExecutionRequest',
                'Required parameter "launchExecutionRequest" was null or undefined when calling executionsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/executions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LaunchExecutionRequestToJSON(requestParameters['launchExecutionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutionFromJSON(jsonValue));
    }

    /**
     * Launch a new execution
     */
    async executionsPost(requestParameters: ExecutionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Execution> {
        const response = await this.executionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all templates
     */
    async templatesGetRaw(requestParameters: TemplatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesGet200Response>> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling templatesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['tenantId'] != null) {
            queryParameters['tenantId'] = requestParameters['tenantId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/templates`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get all templates
     */
    async templatesGet(requestParameters: TemplatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesGet200Response> {
        const response = await this.templatesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete template
     */
    async templatesIdDeleteRaw(requestParameters: TemplatesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling templatesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/templates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete template
     */
    async templatesIdDelete(requestParameters: TemplatesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.templatesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get template by ID
     */
    async templatesIdGetRaw(requestParameters: TemplatesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Template>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling templatesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/templates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateFromJSON(jsonValue));
    }

    /**
     * Get template by ID
     */
    async templatesIdGet(requestParameters: TemplatesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Template> {
        const response = await this.templatesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update template
     */
    async templatesIdPutRaw(requestParameters: TemplatesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Template>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling templatesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['description'] != null) {
            formParams.append('description', requestParameters['description'] as any);
        }

        if (requestParameters['category'] != null) {
            formParams.append('category', new Blob([JSON.stringify(TemplateCategoryToJSON(requestParameters['category']))], { type: "application/json", }));
                    }

        if (requestParameters['documentType'] != null) {
            formParams.append('documentType', new Blob([JSON.stringify(DocumentTypeToJSON(requestParameters['documentType']))], { type: "application/json", }));
                    }

        if (requestParameters['status'] != null) {
            formParams.append('status', new Blob([JSON.stringify(TemplateStatusToJSON(requestParameters['status']))], { type: "application/json", }));
                    }

        if (requestParameters['startDate'] != null) {
            formParams.append('startDate', requestParameters['startDate'] as any);
        }

        if (requestParameters['endDate'] != null) {
            formParams.append('endDate', requestParameters['endDate'] as any);
        }

        const response = await this.request({
            path: `/templates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateFromJSON(jsonValue));
    }

    /**
     * Update template
     */
    async templatesIdPut(requestParameters: TemplatesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Template> {
        const response = await this.templatesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new template
     */
    async templatesPostRaw(requestParameters: TemplatesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Template>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling templatesPost().'
            );
        }

        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling templatesPost().'
            );
        }

        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling templatesPost().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling templatesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['tenantId'] != null) {
            formParams.append('tenantId', requestParameters['tenantId'] as any);
        }

        if (requestParameters['code'] != null) {
            formParams.append('code', requestParameters['code'] as any);
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['description'] != null) {
            formParams.append('description', requestParameters['description'] as any);
        }

        if (requestParameters['category'] != null) {
            formParams.append('category', new Blob([JSON.stringify(TemplateCategoryToJSON(requestParameters['category']))], { type: "application/json", }));
                    }

        if (requestParameters['documentType'] != null) {
            formParams.append('documentType', new Blob([JSON.stringify(DocumentTypeToJSON(requestParameters['documentType']))], { type: "application/json", }));
                    }

        if (requestParameters['startDate'] != null) {
            formParams.append('startDate', requestParameters['startDate'] as any);
        }

        if (requestParameters['endDate'] != null) {
            formParams.append('endDate', requestParameters['endDate'] as any);
        }

        const response = await this.request({
            path: `/templates`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateFromJSON(jsonValue));
    }

    /**
     * Create a new template
     */
    async templatesPost(requestParameters: TemplatesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Template> {
        const response = await this.templatesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
